"""Sample test — auto-generated by goal."""

import os
import tempfile
from pathlib import Path

from tagi.models import Change, ChangeType, Tag
from tagi.config import Config


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    from tagi import models  # noqa: F401


def test_change_creation():
    """Test creating a Change object."""
    change = Change(
        path="test.py",
        change_type=ChangeType.MODIFIED
    )
    assert change.path == "test.py"
    assert change.change_type == ChangeType.MODIFIED
    assert change.tags == []


def test_change_with_tags():
    """Test adding tags to a Change object."""
    change = Change(
        path="test.py",
        change_type=ChangeType.MODIFIED
    )
    change.tags = [Tag.SMALL, Tag.DOCS]
    assert len(change.tags) == 2
    assert Tag.SMALL in change.tags
    assert Tag.DOCS in change.tags


def test_multiple_tags():
    """Test that a change can have multiple tags."""
    change = Change(
        path="README.md",
        change_type=ChangeType.MODIFIED
    )
    change.tags = [Tag.DOCS, Tag.SMALL, Tag.NEW]
    assert len(change.tags) == 3
    assert Tag.DOCS in change.tags
    assert Tag.SMALL in change.tags
    assert Tag.NEW in change.tags


def test_tag_values():
    """Test Tag enum values."""
    assert Tag.SMALL.value == "#small"
    assert Tag.LARGE.value == "#large"
    assert Tag.NEW.value == "#new"
    assert Tag.DOCS.value == "#docs"
    assert Tag.TESTS.value == "#tests"
    assert Tag.CONFIG.value == "#config"
    assert Tag.DEPS.value == "#deps"
    assert Tag.RISKY.value == "#risky"
    assert Tag.REFACTOR.value == "#refactor"
    assert Tag.FEATURE.value == "#feature"


def test_changetype_values():
    """Test ChangeType enum values."""
    assert ChangeType.ADDED.value == "added"
    assert ChangeType.MODIFIED.value == "modified"
    assert ChangeType.DELETED.value == "deleted"
    assert ChangeType.RENAMED.value == "renamed"


def test_change_with_metadata():
    """Test Change object with additional metadata."""
    change = Change(
        path="config.yaml",
        change_type=ChangeType.MODIFIED
    )
    change.tags = [Tag.CONFIG, Tag.RISKY]
    change.lines_changed = 50
    change.risk_score = 0.3
    
    assert change.lines_changed == 50
    assert change.risk_score == 0.3
    assert Tag.CONFIG in change.tags
    assert Tag.RISKY in change.tags


def test_config_loading():
    """Test Config class loads configuration correctly."""
    with tempfile.TemporaryDirectory() as tmpdir:
        config_file = Path(tmpdir) / "tagi.toml"
        config_file.write_text("""
[rules]
"test/" = "#test"

[colors]
"#test" = "blue"

[heuristics]
"api/" = ["#api", "#backend"]
""")
        
        config = Config(tmpdir)
        assert config.get_tag_for_path("test/file.py") == "#test"
        assert config.get_tag_color("#test") == "blue"
        assert config.get_heuristics_for_path("api/user.py") == ["#api", "#backend"]


def test_config_no_file():
    """Test Config class works without configuration file."""
    with tempfile.TemporaryDirectory() as tmpdir:
        config = Config(tmpdir)
        assert config.get_tag_for_path("test.py") is None
        assert config.get_tag_color("#test") is None
        assert config.get_heuristics_for_path("test.py") == []
