"""Sample test — auto-generated by goal."""

import os
import tempfile
from pathlib import Path

from typer.testing import CliRunner

from tagi.models import Change, ChangeType, Tag
from tagi.config import Config
from tagi.planner.grouper import group_changes, group_by_tag, group_by_risk
from tagi.planner.selector import select_by_tags, select_safe_changes
from tagi.composer.commit_message import generate_conventional_message
from tagi.composer.summary import generate_summary
from tagi.executor.git import GitExecutor
from tagi.executor.publish import PublishExecutor


runner = CliRunner()


def test_auto_prefix_with_hash():
    """Test that _ensure_tag_prefix handles tags with # prefix."""
    from tagi.cli import _ensure_tag_prefix
    
    # Tag already has prefix
    result = _ensure_tag_prefix("#small")
    assert result == "#small"
    
    # Tag with different case
    result = _ensure_tag_prefix("#SMALL")
    assert result == "#SMALL"


def test_auto_prefix_without_hash():
    """Test that _ensure_tag_prefix adds # prefix when missing."""
    from tagi.cli import _ensure_tag_prefix
    
    # Tag without prefix
    result = _ensure_tag_prefix("small")
    assert result == "#small"
    
    # Tag without prefix (different case)
    result = _ensure_tag_prefix("docs")
    assert result == "#docs"
    
    # Tag without prefix (multi-word)
    result = _ensure_tag_prefix("feature")
    assert result == "#feature"


def test_auto_prefix_empty_string():
    """Test that _ensure_tag_prefix handles empty string."""
    from tagi.cli import _ensure_tag_prefix
    
    result = _ensure_tag_prefix("")
    assert result == "#"


def test_tag_enum_creation_with_prefix():
    """Test Tag enum creation with # prefix."""
    tag = Tag("#small")
    assert tag.value == "#small"
    assert tag == Tag.SMALL


def test_tag_enum_creation_without_prefix():
    """Test Tag enum creation without # prefix fails."""
    try:
        tag = Tag("small")
        assert False, "Should have raised ValueError"
    except ValueError:
        pass  # Expected


def test_tag_with_prefix_in_filter():
    """Test that tags work with # prefix in filtering."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL]
    
    # Filter with prefix
    tag_enum = Tag("#small")
    filtered = [c for c in changes if tag_enum in c.tags]
    assert len(filtered) == 1


def test_tag_filtering_case_sensitive():
    """Test that tag filtering is case-sensitive."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL]
    
    # Filter with different case should not match
    try:
        tag_enum = Tag("#SMALL")
        filtered = [c for c in changes if tag_enum in c.tags]
        # Tag.SMALL is "#small", not "#SMALL"
        assert len(filtered) == 0
    except ValueError:
        pass  # Tag enum is case-sensitive


def test_tag_filtering_single_tag():
    """Test filtering changes by a single tag."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
        Change(path="README.md", change_type=ChangeType.MODIFIED),
        Change(path="config.yaml", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL, Tag.TESTS]
    changes[1].tags = [Tag.DOCS, Tag.SMALL]
    changes[2].tags = [Tag.CONFIG]
    
    # Filter by SMALL tag
    tag_enum = Tag("#small")
    filtered = [c for c in changes if tag_enum in c.tags]
    assert len(filtered) == 2
    assert filtered[0].path == "test.py"
    assert filtered[1].path == "README.md"


def test_tag_filtering_multiple_tags_or():
    """Test filtering changes with OR logic (any tag matches)."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
        Change(path="README.md", change_type=ChangeType.MODIFIED),
        Change(path="config.yaml", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL, Tag.TESTS]
    changes[1].tags = [Tag.DOCS, Tag.SMALL]
    changes[2].tags = [Tag.CONFIG]
    
    # Filter by TESTS or DOCS (OR logic)
    tags_to_match = [Tag.TESTS, Tag.DOCS]
    filtered = [c for c in changes if any(tag in c.tags for tag in tags_to_match)]
    assert len(filtered) == 2
    assert filtered[0].path == "test.py"
    assert filtered[1].path == "README.md"


def test_tag_filtering_multiple_tags_and():
    """Test filtering changes with AND logic (all tags must match)."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
        Change(path="README.md", change_type=ChangeType.MODIFIED),
        Change(path="config.yaml", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL, Tag.TESTS]
    changes[1].tags = [Tag.DOCS, Tag.SMALL]
    changes[2].tags = [Tag.SMALL, Tag.TESTS, Tag.RISKY]
    
    # Filter by SMALL AND TESTS (AND logic)
    tags_to_match = [Tag.SMALL, Tag.TESTS]
    filtered = [c for c in changes if all(tag in c.tags for tag in tags_to_match)]
    assert len(filtered) == 2
    assert filtered[0].path == "test.py"
    assert filtered[1].path == "config.yaml"


def test_tag_filtering_no_match():
    """Test filtering when no changes match the tags."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
        Change(path="README.md", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL, Tag.TESTS]
    changes[1].tags = [Tag.DOCS, Tag.SMALL]
    
    # Filter by RISKY tag (no matches)
    tag_enum = Tag("#risky")
    filtered = [c for c in changes if tag_enum in c.tags]
    assert len(filtered) == 0


def test_tag_filtering_all_tags_match():
    """Test filtering when all changes match the tag."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
        Change(path="README.md", change_type=ChangeType.MODIFIED),
        Change(path="config.yaml", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL, Tag.TESTS]
    changes[1].tags = [Tag.DOCS, Tag.SMALL]
    changes[2].tags = [Tag.CONFIG, Tag.SMALL]
    
    # Filter by SMALL tag (all match)
    tag_enum = Tag("#small")
    filtered = [c for c in changes if tag_enum in c.tags]
    assert len(filtered) == 3


def test_send_help_uses_repo_path_option():
    """Test that send exposes repo_path as an option and a single positional target."""
    from tagi.cli import app

    result = runner.invoke(app, ["send", "--help"])
    assert result.exit_code == 0
    assert "--repo-path" in result.stdout
    assert "[TARGET]" in result.stdout
    assert "[REPO_PATH]" not in result.stdout


def test_send_invalid_tag_exits_cleanly(monkeypatch):
    """Test that send reports invalid tags without a traceback."""
    from tagi.cli import app

    def fake_scan_repo(_repo_path):
        return [Change(path="test.py", change_type=ChangeType.MODIFIED)]

    def fake_apply_tags(changes, _repo_path):
        changes[0].tags = [Tag.SMALL]
        return changes

    monkeypatch.setattr("tagi.cli.scan_repo", fake_scan_repo)
    monkeypatch.setattr("tagi.cli.apply_tags", fake_apply_tags)

    result = runner.invoke(app, ["send", "not-a-real-tag", "--dry-run"])
    assert result.exit_code == 1
    assert "Unknown tag: #not-a-real-tag" in result.stdout


def test_send_accepts_subcommand_verbose_and_path(monkeypatch):
    """Test that send accepts --verbose after the subcommand and a positional repo path."""
    from tagi.cli import app

    def fake_scan_repo(_repo_path):
        change = Change(path="test.py", change_type=ChangeType.MODIFIED)
        change.lines_changed = 5
        change.risk_score = 0.1
        return [change]

    def fake_apply_tags(changes, _repo_path):
        changes[0].tags = [Tag.SMALL]
        return changes

    monkeypatch.setattr("tagi.cli.scan_repo", fake_scan_repo)
    monkeypatch.setattr("tagi.cli.apply_tags", fake_apply_tags)
    monkeypatch.setattr("tagi.cli.generate_commit_message", lambda *_args, **_kwargs: "test commit")

    result = runner.invoke(app, ["send", ".", "--auto-order", "--dry-run", "--push", "--verbose"])
    assert result.exit_code == 0
    assert "Sending" in result.stdout
    assert "Sorting changes by complexity" in result.stdout
    assert "[DRY-RUN] No changes will be made" in result.stdout


def test_publish_invalid_tag_exits_cleanly(monkeypatch):
    """Test that publish reports invalid tags without a traceback."""
    from tagi.cli import app

    def fake_scan_repo(_repo_path):
        return [Change(path="test.py", change_type=ChangeType.MODIFIED)]

    def fake_apply_tags(changes, _repo_path):
        changes[0].tags = [Tag.SMALL]
        return changes

    monkeypatch.setattr("tagi.cli.scan_repo", fake_scan_repo)
    monkeypatch.setattr("tagi.cli.apply_tags", fake_apply_tags)

    result = runner.invoke(app, ["publish", "not-a-real-tag", "--dry-run"])
    assert result.exit_code == 1
    assert "Unknown tag: #not-a-real-tag" in result.stdout


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    from tagi import models  # noqa: F401


def test_change_creation():
    """Test creating a Change object."""
    change = Change(
        path="test.py",
        change_type=ChangeType.MODIFIED
    )
    assert change.path == "test.py"
    assert change.change_type == ChangeType.MODIFIED
    assert change.tags == []


def test_change_with_tags():
    """Test adding tags to a Change object."""
    change = Change(
        path="test.py",
        change_type=ChangeType.MODIFIED
    )
    change.tags = [Tag.SMALL, Tag.DOCS]
    assert len(change.tags) == 2
    assert Tag.SMALL in change.tags
    assert Tag.DOCS in change.tags


def test_multiple_tags():
    """Test that a change can have multiple tags."""
    change = Change(
        path="README.md",
        change_type=ChangeType.MODIFIED
    )
    change.tags = [Tag.DOCS, Tag.SMALL, Tag.NEW]
    assert len(change.tags) == 3
    assert Tag.DOCS in change.tags
    assert Tag.SMALL in change.tags
    assert Tag.NEW in change.tags


def test_tag_values():
    """Test Tag enum values."""
    assert Tag.SMALL.value == "#small"
    assert Tag.LARGE.value == "#large"
    assert Tag.NEW.value == "#new"
    assert Tag.DOCS.value == "#docs"
    assert Tag.TESTS.value == "#tests"
    assert Tag.CONFIG.value == "#config"
    assert Tag.DEPS.value == "#deps"
    assert Tag.RISKY.value == "#risky"
    assert Tag.REFACTOR.value == "#refactor"
    assert Tag.FEATURE.value == "#feature"


def test_changetype_values():
    """Test ChangeType enum values."""
    assert ChangeType.ADDED.value == "added"
    assert ChangeType.MODIFIED.value == "modified"
    assert ChangeType.DELETED.value == "deleted"
    assert ChangeType.RENAMED.value == "renamed"


def test_change_with_metadata():
    """Test Change object with additional metadata."""
    change = Change(
        path="config.yaml",
        change_type=ChangeType.MODIFIED
    )
    change.tags = [Tag.CONFIG, Tag.RISKY]
    change.lines_changed = 50
    change.risk_score = 0.3
    
    assert change.lines_changed == 50
    assert change.risk_score == 0.3
    assert Tag.CONFIG in change.tags
    assert Tag.RISKY in change.tags


def test_config_loading():
    """Test Config class loads configuration correctly."""
    with tempfile.TemporaryDirectory() as tmpdir:
        config_file = Path(tmpdir) / "tagi.toml"
        config_file.write_text("""
[rules]
"test/" = "#test"

[colors]
"#test" = "blue"

[heuristics]
"api/" = ["#api", "#backend"]
""")
        
        config = Config(tmpdir)
        assert config.get_tag_for_path("test/file.py") == "#test"
        assert config.get_tag_color("#test") == "blue"
        assert config.get_heuristics_for_path("api/user.py") == ["#api", "#backend"]


def test_config_no_file():
    """Test Config class works without configuration file."""
    with tempfile.TemporaryDirectory() as tmpdir:
        config = Config(tmpdir)
        assert config.get_tag_for_path("test.py") is None
        assert config.get_tag_color("#test") is None
        assert config.get_heuristics_for_path("test.py") == []


def test_planner_grouper():
    """Test planner grouper functionality."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
        Change(path="README.md", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL]
    changes[0].lines_changed = 5
    changes[0].risk_score = 0.1
    changes[1].tags = [Tag.DOCS]
    changes[1].lines_changed = 10
    changes[1].risk_score = 0.2
    
    groups = group_changes(changes)
    assert len(groups) == 2
    assert all(hasattr(g, 'name') for g in groups)  # Groups have name attribute


def test_planner_group_by_risk():
    """Test risk-based grouping."""
    changes = [
        Change(path="safe.py", change_type=ChangeType.MODIFIED),
        Change(path="risky.py", change_type=ChangeType.MODIFIED),
    ]
    changes[0].risk_score = 0.2
    changes[1].risk_score = 0.8
    
    risk_groups = group_by_risk(changes, threshold=0.5)
    assert "low_risk" in risk_groups
    assert "high_risk" in risk_groups
    assert len(risk_groups["low_risk"]) == 1
    assert len(risk_groups["high_risk"]) == 1


def test_planner_selector_by_tags():
    """Test tag-based selection."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
        Change(path="README.md", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL, Tag.TESTS]
    changes[1].tags = [Tag.DOCS]
    
    # OR logic
    selected = select_by_tags(changes, [Tag.SMALL, Tag.DOCS], require_all=False)
    assert len(selected) == 2
    
    # AND logic
    selected = select_by_tags(changes, [Tag.SMALL, Tag.TESTS], require_all=True)
    assert len(selected) == 1


def test_planner_select_safe():
    """Test safe changes selection."""
    changes = [
        Change(path="safe.py", change_type=ChangeType.MODIFIED),
        Change(path="risky.py", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.SMALL]
    changes[0].lines_changed = 5
    changes[0].risk_score = 0.1
    changes[1].tags = [Tag.RISKY]
    changes[1].lines_changed = 10
    changes[1].risk_score = 0.8
    
    safe = select_safe_changes(changes)
    assert len(safe) == 1
    assert safe[0].path == "safe.py"


def test_composer_conventional():
    """Test conventional commits generation."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
    ]
    changes[0].tags = [Tag.FEATURE]
    
    message = generate_conventional_message(changes)
    assert message.startswith("feat")


def test_composer_summary():
    """Test summary generation."""
    changes = [
        Change(path="test.py", change_type=ChangeType.MODIFIED),
    ]
    changes[0].lines_changed = 10
    changes[0].risk_score = 0.2
    
    summary = generate_summary(changes)
    assert "1 files" in summary
    assert "10 lines" in summary


def test_executor_git_executor():
    """Test GitExecutor initialization."""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Initialize a git repo
        os.system(f"cd {tmpdir} && git init > /dev/null 2>&1")
        
        executor = GitExecutor(tmpdir)
        assert executor.repo_path == tmpdir
        branch = executor.get_current_branch()
        assert branch in ["main", "master"]


def test_executor_publish_executor():
    """Test PublishExecutor initialization."""
    with tempfile.TemporaryDirectory() as tmpdir:
        executor = PublishExecutor(tmpdir)
        assert executor.repo_path == tmpdir
        assert executor.git is not None


def test_executor_dry_run():
    """Test dry run functionality."""
    with tempfile.TemporaryDirectory() as tmpdir:
        executor = PublishExecutor(tmpdir)
        dry_run = executor.dry_run(["test.py"], "test message")
        
        assert "files" in dry_run
        assert "message" in dry_run
        assert "commands" in dry_run
        assert "git add test.py" in dry_run["commands"]
        assert "git commit -m 'test message'" in dry_run["commands"]
