flowchart LR
%% generated in 0.00s
    subgraph src__tagi
        src__tagi__heuristics___calculate_risk_score["_calculate_risk_score"]
        src__tagi__cli__publish["publish"]
        src__tagi__scanner__scan_repo["scan_repo"]
        src__tagi__providers__detect_provider["detect_provider"]
        src__tagi__cli__list_groups["list_groups"]
        src__tagi__cli__draft["draft"]
        src__tagi__cli__send["send"]
        src__tagi__cli___display_groups["_display_groups"]
        src__tagi__composer___build_title["_build_title"]
        src__tagi__cli___display_changes["_display_changes"]
        src__tagi__heuristics__apply_tags["apply_tags"]
        src__tagi__cli__inspect["inspect"]
        src__tagi__composer__generate_commit_message["generate_commit_message"]
        src__tagi__heuristics___count_lines_changed["_count_lines_changed"]
        src__tagi__cli__scan["scan"]
        src__tagi__planner__group_changes["group_changes"]
        src__tagi__scanner___parse_status["_parse_status"]
    end
    src__tagi__cli__scan --> src__tagi__scanner__scan_repo
    src__tagi__cli__scan --> src__tagi__heuristics__apply_tags
    src__tagi__cli__scan --> src__tagi__cli___display_changes
    src__tagi__cli__list_groups --> src__tagi__scanner__scan_repo
    src__tagi__cli__list_groups --> src__tagi__heuristics__apply_tags
    src__tagi__cli__list_groups --> src__tagi__planner__group_changes
    src__tagi__cli__list_groups --> src__tagi__cli___display_groups
    src__tagi__cli__inspect --> src__tagi__scanner__scan_repo
    src__tagi__cli__inspect --> src__tagi__heuristics__apply_tags
    src__tagi__cli__inspect --> src__tagi__cli___display_changes
    src__tagi__cli__draft --> src__tagi__scanner__scan_repo
    src__tagi__cli__draft --> src__tagi__heuristics__apply_tags
    src__tagi__cli__draft --> src__tagi__planner__group_changes
    src__tagi__cli__draft --> src__tagi__composer__generate_commit_message
    src__tagi__cli__send --> src__tagi__scanner__scan_repo
    src__tagi__cli__send --> src__tagi__heuristics__apply_tags
    src__tagi__cli__send --> src__tagi__planner__group_changes
    src__tagi__cli__publish --> src__tagi__scanner__scan_repo
    src__tagi__cli__publish --> src__tagi__heuristics__apply_tags
    src__tagi__cli__publish --> src__tagi__planner__group_changes
    src__tagi__cli__publish --> src__tagi__providers__detect_provider
    src__tagi__composer__generate_commit_message --> src__tagi__composer___build_title
    src__tagi__scanner__scan_repo --> src__tagi__scanner___parse_status
    src__tagi__heuristics__apply_tags --> src__tagi__heuristics___count_lines_changed
    src__tagi__heuristics__apply_tags --> src__tagi__heuristics___calculate_risk_score
